# Generated by Django 4.1.3 on 2023-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cartlist_table_alter_item_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bn', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('dist', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'ship',
            },
        ),
    ]
